name: Run basic tests in go

on:
  push:
    branches:
      - main

jobs:
  run_basic_tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: install dependencies
        run: go mod tidy
      - name: running go unit test
        run: go test ./...
      - name: running golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.55.2
          args: --timeout=5m --issues-exit-code=0 
